# Generated by Django 3.0.6 on 2020-05-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(fields=('name', 'skill_level'), name='unique_instrument_and_skill'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('city', 'state', 'zip_code'), name='unique_location'),
        ),
    ]
