# Generated by Django 3.0.6 on 2020-05-23 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200522_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Location'),
        ),
    ]
