# Generated by Django 3.0.6 on 2020-05-24 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200523_0041'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instrument',
            name='unique_instrument_and_skill',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location',
        ),
        migrations.AlterField(
            model_name='musician',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Location'),
        ),
    ]
