# Generated by Django 3.0.6 on 2020-05-25 03:04

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200524_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='musician',
            name='videos',
            field=models.ManyToManyField(blank=True, to='account.Video'),
        ),
    ]
